greenery:

  outputs:
    dbt_phisarn:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_phisarn

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_phisarn_bigquery:
      type: bigquery
      method: service-account
      project: dataengineerbootcamp-385813
      dataset: dbt_phisarn
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/dags/dataengineerbootcamp-bigquery-and-gcs.json
      location: asia-southeast1

    prod_bigquery:
      type: bigquery
      method: service-account
      project: dataengineerbootcamp-385813
      dataset: deb_bootcampdataengineercafe
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/dags/dataengineerbootcamp-bigquery-and-gcs.json
      location: asia-southeast1

  target: dbt_phisarn_bigquery